easy_admin:
    site_name: Conférences Livre d'Or

    design:
        menu:
            - { route: 'homepage', 'label': 'Retour à l''accueil', icon: 'home' }
            - { entity: 'Conference', 'label': 'Conférences', icon: 'map-marker' }
            - { entity: 'Comment', 'label': 'Les commentaires', icon: 'comments' }
    entities:
        Conference:
            class: App\Entity\Conference
            label: 'Conférence'
            new:
                title: 'Ajouter une %%entity_label%%'
            edit:
                title: 'Éditer une %%entity_label%%'
        Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            form:
                title: 'Ajouter/Éditer ou Supprimer un commentaire'
            list:
                fields:
                    - 'id'
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image', base_path: '/uploads/photos', label: 'Photo' }
                    - state
                    - { property: 'createdAt', type: 'datetime' }
                sort: [ 'createdAt', 'ASC' ]
                filters: [ 'conference' ]
            new:
                title: 'Ajouter un commentaire'
            edit:
                title: 'Éditer un commentaire'
                fields:
                    - { property: 'conference' }
                    - { property: 'createdAt' , type: datetime, type_options: { attr: { readonly: true } } }
                    - 'author'
                    - { property: 'state' }
                    - 'photoFilename'
                    - { property: 'email', type: 'email' }
                    - text